"""add black mark

Revision ID: 9604ae13a2b2
Revises: cfd2273e6dc7
Create Date: 2024-05-13 13:58:01.378915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9604ae13a2b2'
down_revision: Union[str, None] = 'cfd2273e6dc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plates', sa.Column('black_mark', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plates', 'black_mark')
    # ### end Alembic commands ###
